name: Publish on GitHub, CurseForge & Modrinth

on:
  workflow_dispatch:
    inputs:
      loader:
        description: "Which loader do you want to publish?"
        required: true
        default: "all"
        type: choice
        options:
          - "all"
          - "fabric"
          - "neoforge"

env:
  MINECRAFT_VERSION: 1.21.5
  JAVA_VERSION: 21
  VERSION: 1.1.0+1.21.5
  RELEASE_NAME: Material Beacons 1.1.0 for Minecraft 1.21.5
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        loader: ["fabric", "neoforge"]

    name: Build and Publish (${{ matrix.loader }})
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "${{ env.JAVA_VERSION }}"

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build (${{ matrix.loader }})
        if: github.event.inputs.loader == 'all' || github.event.inputs.loader == matrix.loader
        run: ./gradlew clean :${{ matrix.loader }}:build

      - name: Publish (${{ matrix.loader }})
        if: github.event.inputs.loader == 'all' || github.event.inputs.loader == matrix.loader
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 1025875
          curseforge-token: "${{ env.CURSEFORGE_TOKEN }}"

          modrinth-id: QLLz3XcD
          modrinth-token: "${{ env.MODRINTH_TOKEN }}"

          github-tag: "v${{ env.VERSION }}"
          github-token: "${{ env.GITHUB_TOKEN }}"
          github-generate-changelog: true

          name: "${{ env.RELEASE_NAME }}"
          version: "${{ env.VERSION }}"
          version-type: release
          changelog-file: CHANGES.md

          java: "${{ env.JAVA_VERSION }}"
          files: |
            ${{ matrix.loader }}/build/libs/!(*-@(dev|sources|javadoc)).jar
            ${{ matrix.loader }}/build/libs/*-@(dev|sources|javadoc).jar